name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: Lint Code
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Setup
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Npm Install
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" >> ~/.npmrc
          pnpm install
      - name: Run Linters
        run: pnpm run lint